version: "3.9"
services:
  spark-master:
    image: "master:latest"
    ports:
      - "9090:8080"
    container_name: spark-master
  spark-worker:
    image: "worker:latest"
    ports:
      - "9091:8080"
    container_name: spark-worker
    depends_on:
      - spark-master
